In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [32]:
from mtflearn import ZPs

%matplotlib qt
import numpy as np
import matplotlib.pyplot as plt 

In [49]:
def compute_kernels_weights(n_max=10, size=35):
    zps = ZPs(n_max=n_max, size=size)
    kernels = zps.polynomials
    mask = zps.m > 1
    inds= nm2j(zps.n[mask], -zps.m[mask])
    A_kernels = kernels[mask]
    B_kernels = kernels[inds]

    # compute weights
    theta = np.linspace(0, 2 * np.pi, 361)[0:360]
    ms = zps.m[mask]
    cosmt = np.array([np.cos(m * t) for t in theta for m in ms]).reshape(len(theta), -1)
    sinmt = np.array([np.sin(m * t) for t in theta for m in ms]).reshape(len(theta), -1)
    weights = np.hstack([cosmt, sinmt])  # 360 x 60
    return A_kernels, B_kernels, weights

In [50]:
_, __, w = compute_kernels_weights(n_max=10, size=35)

In [57]:
size = 35
zps = ZPs(n_max=10, size=size)
zm = zps.fit_transform(ps)

zm = zm.unselect(m_unselect=[0,1]).normalize(order=None)
theta = np.linspace(0, 2 * np.pi, 361)[0:360]

# Notice
ms = zm.to_complex().m
cosmt = np.array([np.cos(m * t) for t in theta for m in ms]).reshape(len(theta), -1)
sinmt = np.array([np.sin(m * t) for t in theta for m in ms]).reshape(len(theta), -1)
matrix = np.hstack([cosmt, sinmt])  # 360 x 60

In [37]:
size = 35
num_patches = 100
ps = np.random.rand(num_patches, size, size)

In [48]:
size = 35
zps = ZPs(n_max=10, size=size)
zm = zps.fit_transform(ps)

ms = zm.to_complex().m
mask = ms > 1
ms[mask] == zps.m[zps.m > 1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [30]:
def compute_kernels(n_max, size):
    zps = ZPs(n_max=n_max, size=size)
    kernels = zps.polynomials
    mask = zps.m > 1
    inds= nm2j(zps.n[mask], -zps.m[mask])
    A_kernels = kernels[mask]
    B_kernels = kernels[inds]
    return A_kernels, B_kernels

In [31]:
aa, bb = compute_kernels(n_max=10, size=45)

((25, 45, 45), (25, 45, 45))

In [18]:
import numpy as np
from mtflearn import ZPs
from mtflearn.features import nm2j, nm2j_complex

n_max= 10
size = 45
zps = ZPs(n_max=n_max, size=size)

mask1 = zps.m > 1
mask2 = zps.m < -1
print(zps.m[zps.m>1])
print(zps.m[zps.m<-1])

[ 2  3  2  4  3  5  2  4  6  3  5  7  2  4  6  8  3  5  7  9  2  4  6  8
 10]
[ -2  -3  -4  -2  -5  -3  -6  -4  -2  -7  -5  -3  -8  -6  -4  -2  -9  -7
  -5  -3 -10  -8  -6  -4  -2]


In [10]:
nm2j(zps.n, zps.m)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [14]:
nm2j_complex(zps.n, np.abs(zps.m))

array([ 0,  1,  1,  3,  2,  3,  5,  4,  4,  5,  8,  7,  6,  7,  8, 11, 10,
        9,  9, 10, 11, 15, 14, 13, 12, 13, 14, 15, 19, 18, 17, 16, 16, 17,
       18, 19, 24, 23, 22, 21, 20, 21, 22, 23, 24, 29, 28, 27, 26, 25, 25,
       26, 27, 28, 29, 35, 34, 33, 32, 31, 30, 31, 32, 33, 34, 35])

In [15]:
zps.m

array([  0,  -1,   1,  -2,   0,   2,  -3,  -1,   1,   3,  -4,  -2,   0,
         2,   4,  -5,  -3,  -1,   1,   3,   5,  -6,  -4,  -2,   0,   2,
         4,   6,  -7,  -5,  -3,  -1,   1,   3,   5,   7,  -8,  -6,  -4,
        -2,   0,   2,   4,   6,   8,  -9,  -7,  -5,  -3,  -1,   1,   3,
         5,   7,   9, -10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,
        10])

In [16]:
np.where(zps.m == 0)

(array([ 0,  4, 12, 24, 40, 60]),)

In [17]:
np.where(zps.m > 0)

(array([ 2,  5,  8,  9, 13, 14, 18, 19, 20, 25, 26, 27, 32, 33, 34, 35, 41,
        42, 43, 44, 50, 51, 52, 53, 54, 61, 62, 63, 64, 65]),)

In [28]:
mask = zps.m > 1
print(zps.m[zps.m>1])
print(-zps.m[nm2j(zps.n[mask], -zps.m[mask])])

[ 2  3  2  4  3  5  2  4  6  3  5  7  2  4  6  8  3  5  7  9  2  4  6  8
 10]
[ 2  3  2  4  3  5  2  4  6  3  5  7  2  4  6  8  3  5  7  9  2  4  6  8
 10]


In [ ]:
I have a 1d numpy m, I would like compute a a permutation matrix to reorder this array. for m ==0, it would move to first e